Case #1: 0
Case #2: 2
Case #3: 5
An error happened during execution:
Traceback (most recent call last):
  File "/tmp/tmp5kbu90a_.py", line 91, in <module>
    main()
  File "/tmp/tmp5kbu90a_.py", line 57, in main
    T = next(it)
StopIteration
