Case #1: 2.203697464000E+10
Case #2: 9.813130957182E+14
Case #3: 1.512808311629E+14
Case #4: 3.039098289747E+13
Case #5: 3.261191402237E+14
Case #6: 2.236267556257E+16
Case #7: 1.325068082391E+14
Case #8: 2.115474230454E+15
Case #9: 21888.065047363518
Case #10: 1.0
Case #11: 9.468984662667E+14
Case #12: 8.570678357969E+14
Case #13: 8.521206097494E+14
Case #14: 1.0
Case #15: 1.128291872788E+14
Case #16: 2.519967213942E+15
Case #17: 8.744934195291E+13
Case #18: 1.693147180560E+15
Case #19: 1.051391461270E+15
Case #20: 7.975137262062E+14
Case #21: 19.956349206349206
Case #22: 5.615120516842E+15
Case #23: 2.071811899035E+15
Case #24: 6.079635253169E+14
Case #25: 2.909917132515E+14
Case #26: 2.098344345223E+10
Case #27: 205.97073846891257
Case #28: 227.38605590252325
Case #29: 1.538060848632E+13
Case #30: 4976.622131757481
Case #31: 2.098612288668E+15
Case #32: 8.333333333333332
Case #33: 1.0
Case #34: 1.757503657771E+15
Case #35: 7.3790186125211505
Case #36: 1.452149587990E+14
Case #37: 2.544457246593E+14
Case #38: 1.796525598932E+14
Case #39: 5.361247965762E+12
Case #40: 2.529611231104E+13
Case #41: 8.280701754385966
Case #42: 2.098344345223E+15
Case #43: 7.333333333333333
Case #44: 5.5
Case #45: 2.115474230454E+10
Case #46: 7.028176193309E+14
Case #47: 1.346117454332E+15
Case #48: 11.416666666666666
Case #49: 3.511599205981E+16
Case #50: 11.2710355987055
Case #51: 1.009321013133E+14
Case #52: 4.5
Case #53: 1.583964066592E+15
Case #54: 11.416666666666666
Case #55: 41942.016980818065
Case #56: 6.904026976293E+13
Case #57: 2.445024186548E+15
Case #58: 1.700693339299E+15
Case #59: 28239.738843729905
Case #60: 6.180438150586E+12
An error happened during execution:
Traceback (most recent call last):
  File "/tmp/tmplf2x9ltn.py", line 243, in <module>
    main()
  File "/tmp/tmplf2x9ltn.py", line 228, in main
    T=int(data[0])
IndexError: list index out of range
