Case #1: 1
Case #2: 2
Case #3: 10
An error happened during execution:
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/tmp_4eejunb.py", line 133, in main
    T = int(sys.stdin.readline())
ValueError: invalid literal for int() with base 10: ''
