Case #1: 1 2
Case #2: 2 2
Case #3: 2 1
Case #4: 1 5
Error:
Traceback (most recent call last):
  File "/tmp/tmpj4d3jvd4.py", line 69, in <module>
    main()
  File "/tmp/tmpj4d3jvd4.py", line 44, in main
    j = pos_to_index.pop(p_occ)
KeyError: 5
