Case #1: YES
Case #2: NO
Case #3: YES
Case #4: NO
Case #5: NO
Case #6: YES
Error:
Traceback (most recent call last):
  File "/tmp/tmp6fssjx71.py", line 85, in <module>
    solve_bridge_problem()
  File "/tmp/tmp6fssjx71.py", line 48, in solve_bridge_problem
    T = int(sys.stdin.readline())
ValueError: invalid literal for int() with base 10: ''
