Case #1: 3
Case #2: 10
Case #3: 70
Case #4: 53884207
Case #5: 836094048
An error happened during execution:
Traceback (most recent call last):
  File "/tmp/tmpwaw2gdwj.py", line 43, in <module>
    main()
  File "/tmp/tmpwaw2gdwj.py", line 27, in main
    T = int(sys.stdin.readline())
ValueError: invalid literal for int() with base 10: ''
