Case #1: 1 2
Case #2: 2 4
Case #3: 2 0
Case #4: 1 5
Case #5: 5 0
Case #6: 1 5
Case #7: 2 5
Case #8: 3 5
Case #9: 3 150
Case #10: 4 9
Case #11: 38425 1
Case #12: 212354 3
Case #13: 256013 0
Case #14: 87653 1
Case #15: 176868 1
Case #16: 86026 1
Case #17: 4 14
Case #18: 7 25
Case #19: 1 30
Case #20: 13 36
Case #21: 9 31
Case #22: 23 15
Case #23: 7 34
Case #24: 31 11
Case #25: 15 12
Case #26: 45 4
Case #27: 2 21
Case #28: 1 13
Case #29: 2 15
Case #30: 21 5
Case #31: 23 9
Case #32: 5 163
Case #33: 1 43
Case #34: 7 98
Case #35: 24 14
Case #36: 40 18
Case #37: 8 15
Case #38: 34 17
Case #39: 8 48
Case #40: 12 77
Case #41: 6 47
Case #42: 1 74
Case #43: 9 36
Case #44: 2 125
Case #45: 15 1
Case #46: 21 4
Case #47: 8 97
Case #48: 7 8
Case #49: 11 41
Case #50: 3 0
Case #51: 2 8
Case #52: 6 10
Case #53: 5 102
Case #54: 3 32
Case #55: 5 64
Case #56: 15 37
Case #57: 29 16
Case #58: 19 8
Case #59: 13 12
Case #60: 8 31
Case #61: 5 21
Case #62: 12 12
Case #63: 33 11
Case #64: 10 32
Case #65: 3 4
Case #66: 11 8
Case #67: 27 29
Case #68: 16 12
Case #69: 25 32
Case #70: 2 7
Case #71: 19 25
Case #72: 4 2
Case #73: 4 7
Case #74: 6 40
Case #75: 28 3
Case #76: 8 5
Case #77: 2 63
Case #78: 21 3
Case #79: 30 24
Case #80: 2 27
Case #81: 22 14
Case #82: 6 13
Case #83: 15 11
Case #84: 42 9
Case #85: 1 44
Case #86: 26 10
Case #87: 20 4
Case #88: 19 3
Case #89: 18 2
Case #90: 16 57
Case #91: 41 15
Case #92: 12 25
Case #93: 27 6
Case #94: 2 3
Case #95: 40 11
Case #96: 18 6
Case #97: 31 1
Case #98: 13 5
Case #99: 13 1
Case #100: 4 55
Case #101: 14 21
Case #102: 2 609
Case #103: 17 63
Case #104: 8 162
Case #105: 10 18
Case #106: 6 14
Case #107: 35 3
Case #108: 1 13
Case #109: 29 2
Case #110: 18 1
Case #111: 12 46
Error:
Traceback (most recent call last):
  File "/tmp/tmpoeqsez0c.py", line 85, in <module>
    main()
  File "/tmp/tmpoeqsez0c.py", line 57, in main
    T = int(data[idx]); idx +=1
IndexError: list index out of range
